bashrc: Garuda additions and some own edits
These is a work in progress. I wanted to integrate some Garuda default
configurations into my own. But there's still cleaning work to be done.

diff --git a/home/bashrc b/home/bashrc
--- a/home/bashrc
+++ b/home/bashrc
@@ -37,3 +37,94 @@ done
 for file in `/usr/bin/env ls -1 ${completions}`; do
   source ${completions}/${file};
 done
+
+# temporal fix until I find out from where Garuda is changing my keyboard
+# configuration. Got configured proper keyboard without varian at
+# `/etc/X11/xorg.conf.d/00-keyboard.conf` ,but some other thing is changing it
+# back
+
+# To check current status, there are two ways:
+# localectl status
+# setxkbmap -query
+
+# setxkbmap us
+# echo "Changing keyboard mapping"
+# sudo localectl set-keymap us
+# sudo localectl set-x11-keymap us
+
+# From Garuda
+
+# I didn't like Starship, gonna keep using GBT
+# Load starship prompt if starship is installed
+# if [ -x /usr/bin/starship ]; then
+	# __main() {
+		# local major="${BASH_VERSINFO[0]}"
+		# local minor="${BASH_VERSINFO[1]}"
+
+		# if ((major > 4)) || { ((major == 4)) && ((minor >= 1)); }; then
+			# source <("/usr/bin/starship" init bash --print-full-init)
+		# else
+			# source /dev/stdin <<<"$("/usr/bin/starship" init bash --print-full-init)"
+		# fi
+	# }
+	# __main
+	# unset -f __main
+# fi
+
+# TODO move to my aliases file and add `eza` to required apps
+## Useful aliases
+
+# Replace ls with eza
+if [[ -x /usr/bin/eza ]]; then
+  alias ls='eza -al --color=always --group-directories-first --icons'     # preferred listing
+  alias la='eza -a --color=always --group-directories-first --icons'      # all files and dirs
+  alias ll='eza -l --color=always --group-directories-first --icons'      # long format
+  alias lt='eza -aT --color=always --group-directories-first --icons'     # tree listing
+  alias l.='eza -ald --color=always --group-directories-first --icons .*' # show only dotfiles
+fi
+
+
+# Replace some more things with better alternatives
+if [[ -x /usr/bin/bat ]]; then
+  alias cat='bat --style header --style snip --style changes --style header'
+fi
+
+[ ! -x /usr/bin/yay ] && [ -x /usr/bin/paru ] && alias yay='paru'
+
+# Common use
+alias grubup="sudo update-grub"
+alias fixpacman="sudo rm /var/lib/pacman/db.lck"
+alias tarnow='tar -acf '
+alias untar='tar -zxvf '
+alias wget='wget -c '
+alias rmpkg="sudo pacman -Rdd"
+alias psmem='ps auxf | sort -nr -k 4'
+alias psmem10='ps auxf | sort -nr -k 4 | head -10'
+alias upd='/usr/bin/garuda-update'
+alias dir='dir --color=auto'
+alias vdir='vdir --color=auto'
+alias grep='ugrep --color=auto'
+alias fgrep='ugrep -F --color=auto'
+alias egrep='ugrep -E --color=auto'
+alias hw='hwinfo --short'                          # Hardware Info
+alias biggestPkgs="expac -H M '%m\t%n' | sort -h | nl"     # Sort installed packages according to size in MB (expac must be installed)
+alias gitPkgs='pacman -Q | grep -i "\-git" | wc -l' # List amount of -git packages
+alias ip='ip -color'
+alias vi='nvim'
+alias vim='nvim'
+
+# Get fastest mirrors
+alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
+alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
+alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
+alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"
+
+# Cleanup orphaned packages
+alias cleanup='sudo pacman -Rns $(pacman -Qtdq)'
+
+# Get the error messages from journalctl
+alias jctl="journalctl -p 3 -xb"
+
+# Recent installed packages
+alias rip="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -200 | nl"
+fastfetch -l garuda
