ADd `npx` fallback

diff --git a/src/functions b/src/functions
--- a/src/functions
+++ b/src/functions
@@ -153,3 +153,23 @@ find-biggest-files () {
 
 	find $1 -type f -printf '%s %p\n' | sort --numeric --reverse
 }
+
+# npx fallback when command is not found in $PATH
+command_not_found_handle() {
+  # Do not run within a pipe
+  if test ! -t 1; then
+    >&2 echo "command not found: $1"
+    return 127
+  fi
+  if which npx > /dev/null; then
+    echo "$1 not found. Trying with npx..." >&2
+  else
+    return 127
+  fi
+  if ! [[ $1 =~ @ ]]; then
+    npx --no-install "$@"
+  else
+    npx "$@"
+  fi
+  return $?
+}
